spring.application.name=steam-skin-scheduler
spring.datasource.url=jdbc:mysql://localhost:3306/userid
spring.datasource.username=steamapp
spring.datasource.password=steamapp
spring.jpa.hibernate.ddl-auto=update
spring.show-sql=true
spring.properties.hibernate.format_sql=true
steam.api.community.market.url=https://steamcommunity.com/market/